### ISSUE TITLE
Can I install the singularity in the singularity?

### ISSUE THREAD

**Issue by CristEin** [sylabs/singularity#1064]
Hello,
I have a very immature question: Can I install the singularity in the singularity?
I've tried, but it doesn't seem to work properly. So is there a way to do that?

Thanks in advance!

**Comment by dtrudg** [comment]
Yes, you can. The internal install will need to run unprivileged, using user namespaces.

I would suggest this type of question is asked in the Slack channel or Google Group, as they are more likely to result in discussion with other users. GitHub is best for specific bug or feature requests, rather than usage questions.

* https://singularityce.slack.com/join/shared_invite/zt-t28zjurl-UnsNlmoggF7DcpMrKSR7Fw#/shared-invite/email
* https://groups.google.com/g/singularity-ce
