### ISSUE TITLE
Singularity env value containing a $$ get's converted to random number

### ISSUE THREAD

**Issue by stmlange** [sylabs/singularity#1131]
**Version of Singularity**
```
$ /usr/bin/singularity version
3.10.4-bionic
```

**Describe the bug**
environment variables containing a double $-sign should get passed through, but they get converted into a random number

**To Reproduce**
```
export SINGULARITYENV_MAGIC_FOO='$$'
printenv | grep MAGIC_FOO
singularity exec --cleanenv docker://alpine:3.16.3 printenv | grep MAGIC_FOO
```
which produces `MAGIC_FOO=1388766`

Note that using a different container might produce yet another value for `MAGIC_FOO`
```
singularity exec --cleanenv docker://alpine:3.16.2 printenv | grep MAGIC_FOO
```
which results in `MAGIC_FOO=1388988`

**Expected behavior**
environment variables containing a double $-sign should get passed through,

**OS / Linux Distribution**
Which Linux distribution are you using?
```
$ cat /etc/os-release 
NAME="Linux Mint"
VERSION="19.1 (Tessa)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.1"
VERSION_ID="19.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tessa
UBUNTU_CODENAME=bionic
```

**Installation Method**
Downloaded deb from https://github.com/sylabs/singularity/releases/tag/v3.10.4

**Additional context**
Singularity 3.5.3 doesn't seem to be affected by this:
```
singularity3_5_3 exec --cleanenv docker://alpine:3.16.3 printenv | grep MAGIC_FOO
MAGIC_FOO=$$
```

**Comment by dtrudg** [comment]
Hi @stmlange  - this is, I'm afraid, some confusing behavior but is not considered a bug in 3.10.

Through some of the earlier3.x versions of Singularity, handling of environment changed slightly across versions. This is regrettable, and was not intentional. We were trying to handle some conflicting requirements at the time.

By default, the runscripts that singularity uses in the container, to drive execution, perform a single step of shell evaluation of runtime arguments / env vars. This is what causes the `$$` to be replaced with a process ID.

We added a flag `--no-eval` to prevent this. It is also inferred by the `--compat` flag.

```
11:47 am $ export SINGULARITYENV_MAGIC_FOO='$$'

11:47 am $ singularity exec --no-eval docker://alpine:3.16.3 printenv | grep MAGIC_FOO
INFO:    Using cached SIF image
MAGIC_FOO=$$
```

Alternatively you can escape the `$` to `\$\$`...

```
11:48 am $ export SINGULARITYENV_MAGIC_FOO='\$\$'

11:52 am $ singularity exec docker://alpine:3.16.3 printenv | grep MAGIC_FOO
INFO:    Using cached SIF image
MAGIC_FOO=$$
```

You can read more about the handling here, which explains how and why things work like they do:

https://docs.sylabs.io/guides/3.10/user-guide/environment_and_metadata.html?highlight=eval#escaping-and-evaluation-of-environment-variables

**Comment by stmlange** [comment]
Ok thanks for that insight! I guess since this is then expected behaviour and I can resort to the `--no-eval` I can go ahead and close this issue.

Thanks again!
