### ISSUE TITLE
Why doesn't singularity bind the `/run/user/<ID>` and `/etc/machine-id` paths by default?

### ISSUE THREAD

**Issue by rickstaa** [sylabs/singularity#114]
**Version of Singularity**

What version of Singularity are you using? Run:

```
$ singularity version
3.8.0
```

**Describe the bug**

I noticed that to use several GUI's (e.g. visual studio code, rviz, gedit ect.) I need to bind both the `/run/user/<ID>` folder and the `/etc/machine-id` file. I was wondering why by design, these paths are not bounded when running a singularity container (see [the docs](https://sylabs.io/guides/3.8/user-guide/bind_paths_and_mounts.html?highlight=bind#system-defined-bind-paths) for the currently bounded system paths)?  

Further, I'm also unsure why for singularity containers, the `SESSION_MANAGER` variable is forwarded from the default system as for several of the GUI's, I have to unset this variable for warnings to disappear.

I understand that binding these paths and unsettling the `SESSION_MANAGER` variable might be specific to my use case. I, however, was wondering why the Symlabs team made this design choice? Although this issue is labelled as a bug, it might actually be a question into the default bounding and env forwarding behaviour of the singularity program.

**To Reproduce**

Steps to reproduce the behaviour:

1. Create a ubuntu singularity container using `sudo singularity build --sandbox ubuntu docker://ubuntu:18.04`.
2. Run the new container `sudo singularity run --writable ubuntu`.
3. Install gedit into the container `apt install gedit`.
4. Exit the container.
5. Run the container using the `--nv` flag.
6. Try to start gedit.
7. See it works but throws the following repeated error:

```bash
(gedit:27671): dconf-CRITICAL **: 12:47:35.667: unable to create directory '/run/user/1000/dconf': Read-only file system.  dconf will not work properly.
```

This can be solved by manually binding the `/run/user/<ID>` folder. Further, if people try to open other GUI programs like rviz they receive the following error:

```bash
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000', please create it with 0700 permissions.
dbus[30637]: D-Bus library appears to be incorrectly set up: see the manual page for dbus-uuidgen to correct this issue. (Failed to open "/var/lib/dbus/machine-id": No such file or directory; UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text)
  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)
````

This can be solved by manually binding both the `/run/user/<ID>` and `/etc/machine-id` paths. After doing that the only warning that is left is the following:

```bash
Qt: Session management error: None of the authentication protocols specified are supported
```

This can be solved by unsetting the `SESSION_MANAGER` environmental variable which by default is set to `local/ricks-HP-ZBook-Studio-x360-G5:@/tmp/.ICE-unix/1817,unix/ricks-HP-ZBook-Studio-x360-G5:/tmp/.ICE-unix/1817`.

**Expected behaviour**

I did expect singularity to mount both the `/run/user/<ID>` folder and the `/etc/machine-id` file by default.

**OS / Linux Distribution**

Which Linux distribution are you using?

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Installation Method**

I installed singularity by source using the Symlabs 3.8 documentation.

**Additional context**

Related to:

- https://github.com/hpcng/singularity/issues/3609

**Comment by dtrudg** [comment]
Hi. The answers here are that we don't perform these binds & env var handling by default for simplicity, because the 'correct' behavior is ill-defined, or varies between workflows, and because running desktop applications under Singularity is relatively rare.

If we pass `/run/user/xxx` into the container then we are mixing aspects of the user's session on the host with the container. If you are running a graphical application from a container, but within a desktop environment running on the host, then you want tight integration and access to dbus / pulseaudio / pipewire etc. through the sockets under `/run/user/xxx` might be appropriate. If you are trying to run tools in a container for greater isolation / compatibility across very different host/container OS versions then it is not. Singularity is most commonly used to execute batch and command line workflows, so we avoid the potential issues of mounting `/run/user/xxx` by default.

With regard to `/etc/machine-id` there is no complete consensus on what a container runtime should do. See e.g. https://wiki.debian.org/MachineId . However, the discussion / PR for a mount that has been used in Charliecloud seems like it'd be appropriate: https://github.com/hpc/charliecloud/issues/1050

If you want to mount `/etc/machine-id` by default, you can add it to the `bind path` section in the `singularity.conf` configuration file.

The `SESSION_MANAGER` env var is passed through, as Singularity's default is to pass through almost all host environment. Again, it's not always clear if things should be unset for different workflows. The `SESSION_MANAGER` often goes hand-in-hand with various `XDG_` environment variables which are set when running under an interactive session on the host. These can be inappropriate in a container at times, but at other times their presence results in behavior that is expected (e.g. custom `XDG_CONFIG_DIR` locations).

One thing you can do, is set the runscript in your container definition to `unset SESSION_MANGER` before it runs code, something like...

```
%runscript
    unset SESSION_MANAGER
    code $@
```

Would then likely allow a `singularity run` to work as expected.

**Comment by rickstaa** [comment]
@dtrudg Thanks a lot for the extensive answer! I agree with you that the current behavior makes sense when because running desktop applications under Singularity is relatively rare. I will close this issue since it is easy to work around these issues using the recipe file.
