### ISSUE TITLE
BUILDDIR impedes build reproducibility

### ISSUE THREAD

**Issue by Rubo3** [sylabs/singularity#1173]
Hi, I recently added [singularity-ce](https://aur.archlinux.org/packages/singularity-ce) to the Arch User Repository. The Arch packaging tool `makepkg` warns me that the `singularity` and `run-singularity` binaries contain references to the building directory. By running `singularity buildcfg` I see that it is indeed the case, since the result contains `BUILDDIR`, which points to that directory. This means it is not possible to create a reproducible build of Singularity (Apptainer has the same issue, which is tracked in the [Arch Linux Reproducible Status page](https://reproducible.archlinux.org)). Do you think there are ways to make it so that `BUILDDIR` does not pose a problem to the reproducibility of the project?

**Comment by dtrudg** [comment]
The `BUILDDIR` that is included isn't referenced other than to generate output in the `singularity buildcfg` command, and should be straightforward to remove.

However, I think you'll get tripped up by the `SOURCEDIR` which will also be dependent on where the build was performed. This one is not easy to get rid of because of our use of Go plugins. Due to various limitations of Go plugins, we require that they are built within tree, with the plugin code being in the `SOURCEDIR`. Because `singularity` provides plugin creation and compilation functionality this then requires that we then keep a reference to the `SOURCEDIR` in the executable.

I think what we would have to do here is provide a way for `mconfig` to set a dummy / reproducible SOURCEDIR, which will also disable the ability to build plugins.

I can probably get around to this before the SingularityCE 3.11 release in January, but no guarantees. PRs would be welcome.

**Comment by Rubo3** [comment]
> The `BUILDDIR` that is included isn't referenced other than to generate output in the singularity buildcfg command, and should be straightforward to remove.

This is good to hear, thanks.

> I think what we would have to do here is provide a way for `mconfig` to set a dummy / reproducible SOURCEDIR

Yes that seems reasonable, what about a `--srcdir` option, where `make install` will install the source files? For example you could copy them to `/usr/src/singularity-ce`.

> which will also disable the ability to build plugins.

If we move the source tree to `SOURCEDIR` wouldn't  this still permit to build the plug-ins?

**Comment by dtrudg** [comment]
Sorry for the messing with your comment... I'm working before making coffee and accidentally edited it instead of replying 🤦 - restored your version.

> If we move the source tree to SOURCEDIR wouldn't this still permit the plug-ins to be built?

Sadly, possibly not... there are circumstances in which the absolute path of the source must be identical when compiling a plugin vs when the main program was originally built. Go plugins are very inflexible in this, and on any dependency differences between compile time and plugin build time. Go provides a 'trimpath' to address some of the path issues, but it doesn't work quite as expected with plugins and CGO.

We were able to workaround it for a time, but the method we were using was unsupported and stopped working in Go 1.18.

I can experiment a bit with this... but it's always a time sink. I'll try and implement a dummy BUILDDIR/SRCDIR for 3.11.0 reproducible builds (without plugins), and come back to see how we deal with plugins. We'll need to consider a bit how it fits in with other distro packaging etc. too for that.

**Comment by Rubo3** [comment]
Well that was very quick, thanks!

**Comment by dtrudg** [comment]
> Well that was very quick, thanks!

@Rubo3 - no problem. It will be in the 3.11.0 release, expected in January. Let us know if you come across any other issues.
