### ISSUE TITLE
Singularity for next debian release?

### ISSUE THREAD

**Issue by nileshpatra** [sylabs/singularity#1235]
*Note*: We encourage questions about usage of SingularityCE to be made via the Google Group or Slack channels. Other users frequent these communities, and may already have the answer to your question!

See: https://sylabs.io/singularity#community for links.

**Type of issue**
CVE related commits/information

**Description of issue**
Hi @dtrudg first of all, thanks for your work on singularity. The debian package of [singularity-container](https://tracker.debian.org/pkg/singularity-container) had been lying un-maintained in debian for quite sometime however there has recently been some attempt to revive it.
In general, it looks ok to go into next debian release. and subsequently onto ubuntu and several downstream distributions.
(Needless to say, I am talking about the community edition of singularity here)

However, as you might be aware, debian does not update packages (unless extremely urgent) in its stable release, but at the same time, it is also very particular about security bugs and these need to be addressed urgently. And hence, pushing packages with targetted fixes/minimal patches are still allowed to make it to stable point releases (after approval of stable release managers).
This applies to all packages in stable, including other container related packages like docker/lxc which have been in all last few stable releases.

There are CVEs that keep getting filed against singularity and you keep fixing them. However, on some instances I could not find the exact patch/commit fixing them - or to put it the other way, sylabs has been a bit discrete(?) to reveal the change. For instance an example is [CVE-2021-33622](https://support.sylabs.io/support/solutions/articles/42000087130-3-5-8-security-release-cve-2021-33622-) which does not mention anything in patches except for asking to upgrade. I did raise an issue about this too [at this github issue](https://github.com/sylabs/singularity/issues/586) but this is orthogonal to the current discussion. 

On similar note, I do not see patches for [CVE-2021-32635](https://github.com/sylabs/singularity/security/advisories/GHSA-5mv9-q7fq-9394) and [CVE-2020-13845](https://cve.mitre.org/cgi-bin/cvename.cgi?name=2020-13845) either.

So the question is this - if singularity can go into stable release, would you be able to help out with linking to relevant patches in the CVE and/or in changelog and/or in issues somewhere?

Let me know.

**Comment by dtrudg** [comment]
Hi @nileshpatra - I'm afraid that we cannot commit to providing security related fixes for older versions of SingularityCE over the time-scale of a Debian release.

For the CVE-2021-33622 that you mention, the linked GHSA mentions this, though perhaps not too clearly:

> This issue affects open-source Singularity 3.5.x and 3.6.x. These versions are no longer supported and will not be patched.

Only SingularityPRO 3.5 was patched, which is our long term supported commercial variant.

Note that while our Security Policy does state that announcements...

> will include any patches that are created for legacy versions of Singularity that are no longer being actively maintained by the community.

... our SingularityPRO long-term-supported versions necessarily drift from the open source version from which they were branched. Therefore, not all patches that are developed for an older version SingularityPRO will apply onto the older version open-source tree, in which case they may not be provided.

For security fixes that are made to the open source main branch / current release branch, there should be a commit noting the GHSA / CVE. E.g. see for CVE-2021-32635 at https://github.com/sylabs/singularity/commits/v3.7.4 

What I can do is ensure we link commits in the GHSAs we release, going forward. I can retroactively link to them from the GHSAs on the sylabs/singularity repository. However, the older issues you reference are prior to the SingularityCE fork, and are held on the archived apptainer/singularity repository, which moved from Sylabs, to HPCng, and is now under the control of the Apptainer project.

One thing I should mention is that we've recently started packaging for EPEL, which does have expectations of backporting and avoiding incompatible updates where possible. This does mean that going forward the situation will be a little different. EPEL's policy is less restrictive than Debian's stable release however - so again, I cannot commit to patches being available throughout the lifetime of a Debian stable release.

Finally, I would sincerely appreciate that if Debian is providing singularity-ce in a stable release that:

* The full e2e-test suite is run
* A note to users is provided, somewhere appropriate, explicitly stating that the package has not been built with the upstream versions of dependencies, and may contain patches.

I realise that we can't require this, but we would like to avoid issues such as https://github.com/sylabs/singularity/issues/852 being reported upstream - and we'd anticipate this being more common if the package enters Debian stable. 

The ability to bundle our dependencies is one reason why we have now proceeded with EPEL packaging at this point, but haven't engaged with Debian, where aggressive unbundling is required.

**Comment by nileshpatra** [comment]
Hi David, I'm now a bit confused on the way forward :-)
I am tempted to get it to stable, but I too am unsure. I started a mail thread on -devel mailing list a while ago.

I am replying on the thread to seek for more opinions. I am keeping you in CC (I hope you do not mind).

**Comment by dtrudg** [comment]
> Hi David, I'm now a bit confused on the way forward :-) I am tempted to get it to stable, but I too am unsure. I started a mail thread on -devel mailing list a while ago.
>
> I am replying on the thread to seek for more opinions. I am keeping you in CC (I hope you do not mind).

:+1:


I have now added a direct link to the patch for CVE-2021-32635 on the GHSA we control at:

https://github.com/sylabs/singularity/security/advisories/GHSA-5mv9-q7fq-9394

If you would like them retroactively added for the older CVEs, prior to the singularity-ce fork, then I'd suggest that needs to be raised with the apptainer org. Although I might have created them, they are now located at https://github.com/apptainer/singularity/security/advisories and I can't edit them.

**Comment by dtrudg** [comment]
I have also added direct links to patches on the GHSAs for CVEs on our close singularity dependencies...

- https://github.com/sylabs/sif/security/advisories/GHSA-m5m3-46gj-wch8
- https://github.com/sylabs/sif/security/advisories/GHSA-4gh8-x3vv-phhg

Hope this helps, albeit in a limited manner.

**Comment by nileshpatra** [comment]
Thanks a bunch. To be clear, I am currently not looking for patches in older release, as I'd push the latest singularity version, whatever comes out in next couple of months, but I'd need patches for the next three years or so until the release is officially supported and point releases happen.

Again, thanks a lot for being so prompt and nice! I'll see what comes out of the situation.

**Comment by dtrudg** [comment]
> Thanks a bunch. To be clear, I am currently not looking for patches in older release, as I'd push the latest singularity version, whatever comes out in next couple of months to upcoming stable, but I'd need patches for CVEs for the next three years or so until the stable release is officially supported and debian stable point releases happen.

Going forward, it's probably best to consider this in the context of our release lifecycle. It doesn't guarantee three years. The actual timespan on patch availability for a for CE x.y is in the range of 6 months to 2 years*, depending on whether the release becomes a commercial SingularityPRO release.

Outside of that, you'd have to do the backport work yourself, from whatever fixes are applied to the main branch, or latest stable branch of CE.

https://github.com/sylabs/singularityce-community/blob/main/roadmap.md#Development-Cycle

SingularityCE generally has a new minor (or major) release approx. every 6 months. We generally turn every second minor release into a long-term supported commercial SingularityPRO version, and our security policy means *most* (but not all) security patches against PRO (i.e. ones that would be applicable to the CE version from which it was branched) will be available.

As an example....

SingularityCE 3.10.x is *not* going to be a SingularityPRO release. So, when SingularityCE 3.11 comes out, 3.10.x is unsupported. No further patches will be issued for it security or otherwise.

When SingularityCE 3.11 comes out, it will spend ~6 months as the current CE release, in which time it will receive patches directly.

Because SingularityCE 3.11 will become SingularityPRO 3.11, limited security patches we apply to PRO 3.11 will be made available, as diffs only, for the lifetime of that PRO version, where they apply to the CE release from which it is branched. We will not make a new release of CE 3.11 ourselves that incorporates these changes. Additionally, security fixes for PRO 3.11 that are patches that don't apply to CE (due to drift between PRO and CE during the PRO LTS period) will not be provided for CE.

Really, the model is that open-source users need to follow the latest CE version. We provide patches for some situations, but generally the expectation is on distributions to backport as necessary from the current CE version if they want to keep an older version of SingularityCE in a stable release long-term. This will require Golang knowledge, and also acceptance of the need to handle aggressive dependency version changes.

Even on our current stable branch we track dependency updates closely. We also only target the latest 2 releases of Go, per their upstream security policy. I'm away that the way these common practices in the Go world don't really match well with the requirements of Debian stable are well covered in the discussions around packaging many other things, like Docker, and podman.

> Again, thanks a lot for being so prompt and nice! I'll see what comes out of the situation.

**Comment by dtrudg** [comment]
It looks like this has almost played out on the Debian mailing list. I'll close the issue here.

**Comment by nileshpatra** [comment]
Hi @dtrudg 

Thanks for chiming into the discussion. As it was told that it won't be possible for singularity to support "LTS" sort of releases, and that backporting CVEs would require quite some (a lot of?) efforts, and the security team isn't super happy about it as well, unless someone commits to doing this work. I maintain 230+ packages in debian, and adding this overhead is impractical for me to maintain in in stable, considering that no other debian contributor stepped up thus far to help with this release.

Thus, I've decided to not go ahead with a stable release this time, and I'm a bit sad for the situation, as I put quite a lot of effort to get singularity's debian package (which was in a dilapidated condition) to be in a good shape. But that being said, I plan to distribute this package to stable via [fasttrack.debian.net](https://fasttrack.debian.net/). It is maintained by Debian developers, and it is a good way to get packages up and running into stable, which conform to debian-packaging standards. I hope that'd help stable users somewhat.

Thanks for all your comments so far, and thanks for being a lovely upstream developer!
