### ISSUE TITLE
failed to copy: io: read/write on closed pipe

### ISSUE THREAD

**Issue by jpfeuffer** [sylabs/singularity#1302]
**Version of Singularity**
3.10.4

**Describe the bug**
Trying to upload images to ghcr.io with singularity push. But it randomly fails 1 out of maybe 5-10 times.

**To Reproduce**
See https://github.com/OpenMS/OpenMS/actions/runs/4119370616/workflow

**Expected behavior**
Upload successfully *all* the time.

**OS / Linux Distribution**
quay.io/singularity/singularity:v3.10.4 on Githubs ubuntu-latest

**Installation Method**
quay.io/singularity/singularity:v3.10.4

**Additional context**
Maybe this is relevant, which was just recently fixed. It is *exactly* the same error. https://github.com/containerd/containerd/issues/7972

**Comment by dtrudg** [comment]
Hi @jpfeuffer - probably this is an issue that is inherited from containerd/containerd via it's use in oras-project/oras-go that we use to interact with registries via `oras://`.

We have recently bumped our containerd dependency to the latest... so there's a good chance it will be fixed in the 3.11.0 release tomorrow.... or if you build from the head of the `release-3.10` branch.

I'm afraid we do not maintain the quay.io/singularity/singularity images, so we can't say when a new version will be available there.

**Comment by jpfeuffer** [comment]
Ah nice. I was "hoping" for a dependency. I will report back once we upgrade. What's the best supported way of installing? We also need spython, since we want to convert Dockerfiles. I think we just wait and hope the quay containers will not take too long to update.

Glad you found OpenMS useful :) We think the same about Singularity.

**Comment by dtrudg** [comment]
I believe this is fixed with the update. I haven't been able to trigger it... let us know if you see it occuring with 3.11.0.

**Comment by jpfeuffer** [comment]
Hi! I just tried today with 3.11.0 but now I get:
`ERROR  : Requesting capability set 0x000001ffffffffff while permitted capability set is 0x0000003fffffffff`

https://github.com/OpenMS/OpenMS/actions/runs/4324500649/jobs/7549408947

**Comment by dtrudg** [comment]
Hi @jpfeuffer - please could yo open a new issue for this with details on what distribution you are using, how singularity is installed / run etc. 

Haven't seen any capability set issues in our testing, so I'm not sure what's going on here.
