### ISSUE TITLE
Error reading manifest - OCI index found, but accept header does not support OCI indexes

### ISSUE THREAD

**Issue by jonahcullen** [sylabs/singularity#1312]
**Version of Singularity**
3.5.2

**Describe the bug**
Trying to build image from docker ubuntu results in the following error

```
While performing build: conveyor failed to get: Error reading manifest 20.04 in docker.io/library/ubuntu: manifest unknown: OCI index found, but accept header does not support OCI indexes
```

**To Reproduce**
The `test.def` file contains

```
Bootstrap: docker
From: ubuntu:20.04
```

and build with `sudo singularity build --tmpdir /scratch/test/tmp test.sif test.def`.

**Expected behavior**
A singularity image! This has worked just fine up until very recently. `From: ubuntu:latest` returns the same error but `From: alpine:latest` builds successfully. I can see from the docker hub that ubuntu 20.04 has been recently updated so perhaps it is on their end?

**OS / Linux Distribution**
18.04.3 LTS (Bionic Beaver)

**Comment by dtrudg** [comment]
>3.5.2

I'm afraid that this is an old version of Singularity from Dec 2019, that no longer receives any support or fixes.

Ubuntu recently changed their official docker hub image builds, and they now use `.oci.` mediatypes instead of `.docker.` mediatypes.

You will need to upgrade to a current version of singularity, which uses an updated dependency for handling docker/oci images that handles the change.

**Comment by dtrudg** [comment]
FYI - it's not possible to pull ubuntu:latest with a 2019 version of Docker, any more, either:

https://github.com/docker-library/official-images/issues/14025#issuecomment-1423743224

**Comment by jonahcullen** [comment]
Ah okay thank you very much! I ended up upgrading singularity to 3.11.0 and all is now well.
