### ISSUE TITLE
No loop devices available for multiple singularity shells in specific kernel

### ISSUE THREAD

**Issue by LarsRhijns** [sylabs/singularity#1499]
**Version of Singularity**
3.10.5-focal

**Describe the bug**
Since a few days I have issues running a second (or more) singularity shells. The first launches as it always did before, from the second one and onwards I get the following error message:
```
FATAL:   container creation failed: mount /proc/self/fd/3->/var/lib/singularity/mnt/session/rootfs error: while mounting image /proc/self/fd/3: failed to find loop device: could not attach image file to loop device: no loop devices available
```
After a lot of searching online I somehow found the workaround by running `$ sudo losetup -f` in a new terminal, to somehow find a loop device which as to my knowledge was already free. After running this command I can run a new parallel singularity shell, but only in this particular terminal. Trying to launch another requires the losetup command to be ran as well.

After some more searching I noticed it was dependent on my kernel version: `5.15.0-69-generic`. Rolling back to `5.15.0-46-generic` while booting fixes the issue completely. 

**To Reproduce**
I've tried many singularity container files, it does not seem to matter as far as I know. Simply be running either singularity `3.10.2` or `3.10.5` (maybe other versions as well) on kernel version `5.15.0-69-generic` and launching with `$ singularity shell -p <any .sif/.simg>` will create the error message above. 

**Expected behavior**
Expected is for the command `$ singularity shell -p <any .sif/.simg>` to have no issues with multiple terminals running more singularity shells. 

**OS / Linux Distribution**
```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
(I also had the issue on a 22.04 partition, but already removed the partition in the meantime...)

**Installation Method**
I installed Singularity from [here](https://github.com/sylabs/singularity/releases/tag/v3.10.5) or [here](https://github.com/sylabs/singularity/releases/tag/v3.10.2) using the focal and jammy .deb downloads, and running dpkg to install followed by a `$ sudo apt install -f`. 

**Additional context**
This issue seems to be kernel-version dependent. Probably more other kernel versions will solve this issue. For me the kernel version that causes this issue is `5.15.0-69-generic`. Peers working with similar setups using `5.15.0-67-generic` seem to be not having this issue already, so downgrading all the way to `5.15.0-46-generic` seems not necessary but was the only one I specifically still had installed.

**Comment by lunjohnzhang** [comment]
I am having exactly the same error with `singularity-ce version 3.11.1-focal` on Ubuntu 20.04. For me downgrading the kernel version to `5.15.0-67-generic` resolves the issue.

**Comment by marioney** [comment]
This seems to be related to https://github.com/apptainer/apptainer/issues/1258

The proposed workaround there is:

> edited singularity.conf and allowed the sharing of loop devices.

**Comment by dtrudg** [comment]
This has clearly been localized to the Ubuntu 20.04 linux-generic kernel updates corresponding to https://ubuntu.com/security/notices/USN-5982-1

However, it isn't clear to me how the updates listed there would be relevant to loop device calls. It's not trivial to see if other code that may be relecant was modified, so this will take some time to investigate further.

If you observe the issue on any distribution _other than_ Ubuntu 20.04, please give detail of the kernel version, distro version etc. Thank you.

**Comment by dtrudg** [comment]
Confirmed on a VM running `5.15.0-69-generic` and not an issue on `5.15.0-67-generic`.

This appears to be related to a non-security related patch brought in for this update:

> - loop: Fix the max_loop commandline argument treatment when it is set to 0

https://kernel.ubuntu.com/git/ubuntu/ubuntu-focal.git/commit/?h=hwe-5.15-next&id=8d5c96dd3c7ed64e9beaab0d47766e4c8a18d66a

It appears that the patch means that the kernel now sets `max_loop` to the kernel config value of `CONFIG_BLK_DEV_LOOP_MIN_COUNT`, unless `max_loop` is specified as an option. `CONFIG_BLK_DEV_LOOP_MIN_COUNT` is set to `8` on Ubuntu. By default Ubuntu will consume several loop devices for snaps, so a 2nd singularity container run will hit the limit. This appears as though it might be a bug, but perhaps it is intentional behaviour for the upstream kernel patch?

```
$ grep DEV_LOOP /boot/config-5.15.0-69-generic 
CONFIG_BLK_DEV_LOOP=y
CONFIG_BLK_DEV_LOOP_MIN_COUNT=8
CONFIG_AUFS_BDEV_LOOP=y
```

**Solution**

On this kernel, you will need to configure `max_loop` for the `loop` driver to a higher value. Suggest setting it to the same as `max loop devices` in `singularity.conf`, which is 256 by default.

You must do this with a kernel CMDLINE entry, because `loop` is compiled into the kernel on Ubuntu. It is not a module.

1. Add `max_loop=256` to the `GRUB_CMDLINE_LINUX` value in `/etc/default/grub`
2. Run `update-grub2` as root.
3. Reboot the system.
4. `cat /proc/cmdline` and verify `max_loop=256` is present.

After this, Singularity should work as normal.

There's nothing we can do in Singularity to work around this, as `max_loop` is a kernel enforced limit to the number of loop devices. I suspect the same issue will affect some Ubuntu users via snap at some point, and it will be addressed in some manner.

**Comment by nevesLiliane** [comment]
> This seems to be related to [apptainer/apptainer#1258](https://github.com/apptainer/apptainer/issues/1258)
> 
> The proposed workaround there is:
> 
> > edited singularity.conf and allowed the sharing of loop devices.

Author of [apptainer/apptainer#1258](https://github.com/apptainer/apptainer/issues/1258) here, this solution worked for a very brief time.

**Comment by dtrudg** [comment]
> > This seems to be related to [apptainer/apptainer#1258](https://github.com/apptainer/apptainer/issues/1258)
> > The proposed workaround there is:
> > > edited singularity.conf and allowed the sharing of loop devices.
> 
> Author of [apptainer/apptainer#1258](https://github.com/apptainer/apptainer/issues/1258) here. This "solution" worked for a very brief time.

Setting `shared loop devices` won't help a lot... it'll just allow you to run more copies of the same container. You need to ensure `max_loop` is set for a proper fix here.

**Comment by dtrudg** [comment]
The issue was raised with Ubuntu by others here: https://bugs.launchpad.net/ubuntu/+source/linux-hwe-5.15/+bug/2013086

**Comment by ptrebert** [comment]
Just in case somebody else stumbles upon this, this solution is working on `5.15.0-70-generic`:
https://github.com/sylabs/singularity/issues/1499#issuecomment-1493908443

Updating Singularity to 3.11.x does not fix the issue, only the above solution works.
