### ISSUE TITLE
pod failed to start on Kubernetes cluster with Singularity-CRI

### ISSUE THREAD

**Issue by anshadmohammed** [sylabs/singularity#1552]
The pod fails to start  on Kubernetes cluster with Singularity-CRI. I could see below errors from logs. Do you have any idea what could be the cause of this problem? Please let me know if you need any additional information!

Response: null
Error: rpc error: code = Internal desc = could not run pod: could not spawn pod: could not create pod: could not execute create container command: exit status 1
Error for command "oci": unknown flag: --empty-process

**Comment by dtrudg** [comment]
The singularity-cri project has been archived, and is not maintained or supported. Please see the note on the repository here: https://github.com/sylabs/singularity-cri#singularity-cri

![image](https://user-images.githubusercontent.com/4522799/231698561-6b95c01b-c101-4748-b694-6d367d6b501f.png)

As it has not been maintained since 2020, errors would be expected on newer kubernetes clusters, as k8s develops at a fast pace.

You may be interested in the following fork that was created by a user:

https://github.com/Nienkeeijsvogel/singularity-cri

https://groups.google.com/g/singularity-ce/c/sGc8KVwhhHo/m/vbUe89ecBQAJ
