### ISSUE TITLE
root filesystem extraction failed: extract command failed: ERROR : Failed to create user namespace

### ISSUE THREAD

**Issue by suhuanhou** [sylabs/singularity#1741]
Hey! I'm using singularity with version 3.7.1 in order to use Demuxify.sif.

I install with conda environment:
conda install -c conda-forge singularity

the code problem is:
$ singularity exec Demuxafy.sif Combine_Results.R -h
INFO: Converting SIF file to temporary sandbox...
FATAL: while extracting Demuxafy.sif: root filesystem extraction failed: extract command failed: ERROR : Failed to create user namespace: user namespace disabled
: exit status 1

Thank youu in advance!

**Comment by dtrudg** [comment]
User namespaces are not enabled on the system. Please see the documentation:

https://docs.sylabs.io/guides/latest/admin-guide/user_namespace.html#user-namespace-requirements

As this is a usage issue rather than a bug or feature request, please follow up in GitHub discussions, Slack, or on the Google Group if you have further questions.
