### ISSUE TITLE
Disable --uts option in singularity.conf

### ISSUE THREAD

**Issue by sinirajapan** [sylabs/singularity#1767]
【Request】
　In singularity.conf, add ’allow userns' and 'allow uts ns' like 'allow pid ns'.

【Background】
  EDA (Electronic design automation)  tool uses FlexLM (https://www.flexera.com/) for license management.
It is possible to restrict the access source of the license, and provides restrictions using "username" and "hostname"
 
【Theme】
  When running the EDA tool in an environment that uses singularity, singularity exec --hostname ok_machine eda.sif eda_exec
By doing so, the above restrictions can be passed by disguising the hostname.
This is an issue that should be solved by FlexLM and/or EDA tools, but the situation is that singularity cannot be introduced because the developer does not support it.
Similarly, by binding /etc/passwd, the user name is changed and the above restrictions can be passed.

**Comment by sinirajapan** [comment]
Not only --uts option but also disabling --hostname.

**Comment by dtrudg** [comment]
This is not really going to be an effective way of avoiding the issue. You would, instead, have to disable unprivileged user namespaces on the system entirely.

On most systems these days, `unshare` is available. A user can `unshare -u -r` to get a user namespace with UTS namespace outside of Singularity. They can then set the hostname directly with the `hostname` command.

```
$ whoami
dtrudg-sylabs
$ hostname
mini
$ unshare -u -r

$ whoami
root
$ hostname bob
$ hostname
bob
```

Disabling the user & UTS namespaces in `singularity.conf` is therefore not effective. It would have to be done for the whole system by disabling unprivileged user namespaces with a `sysctl`. Otherwise there are easy ways to work around the configuration.

In general we prefer to avoid adding configuration options that infer some kind of security-related restriction that can easily be bypassed.

**Comment by sinirajapan** [comment]
We've already disable user namespaces with sysctl to disable 'unshare -r'.

Other namespaces are also used by systemd on RHEL9(network, uts, etc.), so we want to keep them available.

But I don't want to be able to use it in singularity.

**Comment by dtrudg** [comment]
Okay. I think we'd consider a PR contributing this, but it's not a high priority to develop unless it affects a broad range of users.
