### ISSUE TITLE
check-pkg-no-buildcfg CI check not working

### ISSUE THREAD

**Issue by DrDaveD** [sylabs/singularity#1823]
We found when attempting to import #1699 into an apptainer feature branch that your check-pkg-no-buildcfg is apparently not working.  I don't know why the difference, but if I run the commands by hand on the current sylabs/singularity main branch, it finds that these modules include buildcfg:
```
github.com/sylabs/singularity/pkg/ocibundle/native
github.com/sylabs/singularity/pkg/ocibundle/sif
github.com/sylabs/singularity/pkg/ocibundle/tools
```

**Comment by DrDaveD** [comment]
That's because `pkg/ocibundle/tools/overlay_linux.go` includes `internal/pkg/util/fs/overlay` which includes `internal/pkg/util/bin` which includes `internal/pkg/buildcfg`.

**Comment by dtrudg** [comment]
Yes - missing things that go through a chain of imports like that is a known issue unfortunately, that has caught us out once before. The check isn't perfect. If you have an easy fix then a PR would be appreciated.

We have a standing task for the 4.0 release to address pkg vs internal properly...

https://github.com/sylabs/singularity/issues/80

The work in the main branch on `--oci` mode is unreleased, and should be considered under development. Because this isn't a bug in singularity from a user perspective, and the issue is developer focused in un-released code only... I'm going to remove the bug label.

**Comment by dtrudg** [comment]
@DrDaveD As an aside... where are you maintaining a feature branch that is pulling in all of the `--oci` work? I'm not able to find it from the Apptainer main repo.

It had been my understanding from previous discussion, that Apptainer wasn't going to pursue bringing in `--oci` mode as there were questions as to whether it was relevant for your user base?

**Comment by DrDaveD** [comment]
It's in https://github.com/edytuk/apptainer/tree/oci-action, just in case it might be wanted someday.

**Comment by dtrudg** [comment]
> I don't see what's wrong with the check. As I said, it works for me interactively, and the exact same test in apptainer catches it.

Yeah - I'll look into it again at some point. It's an interesting point that the test in apptainer... so GitHub actions rather than CircleCI... catches it.

> I also didn't know why it was a problem for buildcfg to be included from pkg, but I guess your explanation that the code is supposed to be usable by other packages is the reason -- anything using buildcfg would not be friendly for outside users.

It's a sort of 'pseudo-standard' in Go modules that anything in `pkg/` should be importable by other projects and dependable. If code is using buildcfg then it's not something that can be imported and used without the 3rd party project building singularity or coming up with some GEN step to generate a dummy buildcfg.

We basically decided to follow...

https://github.com/golang-standards/project-layout#pkg

It's not a true standard, and has been contraversial... but at least the expectations for `pkg/` are pretty widespread.
