### ISSUE TITLE
Singularity on Windows?

### ISSUE THREAD

**Issue by lonnietc** [sylabs/singularity#2282]
Hello,

I am seeking a simple cross-platform container system to include using it on Windows to run some headless serves, but not use WSL if possible.

Any thoughts?

Thanks

**Comment by preminger** [comment]
There is no containerization solution that runs on Windows without a Linux layer _somewhere_. To simplify things slightly, containerization works by running a different OS atop an existing kernel, so that the existing kernel can serve as the de facto kernel for the different OS you want to run. Therefore, if you want to run Linux OSes inside your containers, there has to be an actual Linux kernel running outside them somewhere.

This by the way is the reason why Docker, for example, needs to spawn a virtual machine (via VirtualBox, VMware, etc.) when running on Windows but not when running natively on Linux.
