### ISSUE TITLE
Singularity cannot run Docker file using avx2 instructions

### ISSUE THREAD

**Issue by regevs** [sylabs/singularity#2496]
**Version of Singularity**
```
$ singularity --version
singularity-ce version 3.11.5
```

**Describe the bug**
I built a docker image of a binary compiled to use avx2 instructions, and pushed it to docker.io. On the same node I used to build the image, Docker can run the image without a problem:
```
$ docker run docker.io/regevsch/gamma_smc:v0.2-alpha --help
[prints output of my program as expected]
```
However, singularity does not:
```
$ singularity run docker://docker.io/regevsch/gamma_smc:v0.2-alpha --help
INFO:    Using cached SIF image
Illegal instruction
```
I know that "Illegal instruction" arises when a binary tries to use an incompatible instruction set, but this is the same computer used to build the image, and I know the binary compiles and runs, both directly in the environment or within Docker, as shown above. 

Also, in another computer and environment, `apptainer version 1.2.5-1.el8` runs this docker image with no problem.

**To Reproduce**
```
singularity run docker://docker.io/regevsch/gamma_smc:v0.2-alpha --help
```

**Expected behavior**
It should run.

**OS / Linux Distribution**
Which Linux distribution are you using?
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Installation Method**
It is provided as a module by my system (the Sanger Institute at Cambridge, UK).

**Additional context**
This is the Docker file:
```
FROM ubuntu:24.04

RUN apt-get update && apt-get -y upgrade
RUN apt-get -y -qq install wget unzip make gcc-12 g++-12 bzip2 zlib1g-dev libbz2-dev liblzma-dev

# Install the g++/gcc defaults
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 100 && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100 && \
    update-alternatives --install /usr/bin/cc gcc /usr/bin/gcc-12 100    

# Download boost
RUN wget -q https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.bz2 && \
    tar xjf boost_1_81_0.tar.bz2

# Install boost
RUN cd ./boost_1_81_0 && \
    ./bootstrap.sh --with-libraries=filesystem,iostreams,system,program_options --with-toolset=gcc && \
    ./b2 -j 8 install

# Download and install zstd
RUN wget -q https://github.com/facebook/zstd/releases/download/v1.5.4/zstd-1.5.4.tar.gz && \
    tar xvf zstd-1.5.4.tar.gz && \
    cd zstd-1.5.4 && \
    make -j 8

# Download and install htslib
RUN wget -q https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2 && \
    tar xjf htslib-1.17.tar.bz2 && \
    cd htslib-1.17 && \
    ./configure && \
    make -j 8 && \
    make install

# Set env vars
ENV CPATH=/zstd-1.5.4/lib:/htslib-1.17
ENV LIBRARY_PATH=/zstd-1.5.4/lib:/usr/local/lib
ENV LD_LIBRARY_PATH=/zstd-1.5.4/lib:/usr/local/lib

# Copy and build Gamma-SMC
COPY . /home/
RUN cd /home/ &&\
    make && \
    cp /home/bin/gamma_smc /usr/local/bin/gamma_smc

# Define entry point
ENTRYPOINT ["gamma_smc"]
```

Where the working directory is the cloned repo from: `https://github.com/regevs/gamma_smc`.

**Comment by dtrudg** [comment]
Singularity doesn't have any effect on the instruction set that's supported on a system. Because it doesn't virtualize the CPU, it cannot change what is supported.

What is the CPU on the system where the container was built, but doesn't run? What is the CPU where the container runs with Apptainer?

Software can be compiled with flags that result in architecture specific instructions that are not supported on the machine the compilation is performed on. Just because the software compiles correctly, doesn't mean it can run on the machine where it was compiled.

**Comment by dtrudg** [comment]
If there is a remote docker daemon used for the build... are you certain that when you are later running the container with docker it is executing on the first (Broadwell) machine - and not where the docker daemon is? What do you see if you run `lscpu` inside a docker container?

We need to be certain that a docker container is seeing the same CPU that a singularity container is running on.

From the `lscpu` output you have given, the first machine is not a bare-metal physical machine. Instead, it is a virtual machine running under KVM. It is emulating a specific CPU architecture.

<img width="445" alt="Screenshot 2024-01-08 at 09 29 16" src="https://github.com/sylabs/singularity/assets/4522799/2709b22d-e4d7-44c1-970d-41c6d1bd8cdc">

It is possible that the particular virtual machine configuration / flags it advertises are resulting in code being built that cannot be executed on the real host CPU that is underneath the VM. It's hard to tell, though.

There are numerous reports about various software encountering illegal instruction errors when run on cloud instances / virtual machines even when the avx2 flag is advertised in `/proc/cpuinfo`.

If you compile without `-mavx2` is everything working? (ruling out the potential issue of some other instruction being the actual cause).

To avoid issues with CPU detection on virtual machines, you may want to find out from the administrators what the true underlying CPU is for the VM - and then use specifc `-march=` rather than `-march=native`.

I am not surprised everything works under apptainer on the seconf machine, as it is bare-metail (not a virtual machine), and the CPU model is recent, supporting features long after avx2.

**Comment by regevs** [comment]
I cannot compile without `-mavx2` (I use special AVX2 instructions). But indeed when I compile without `-march-native` it works well. I will explicitly use `-march=x86-64` for the docker image, which seems to work.

It would still be good to understand why this failed. Future users of my image should be able to run this image on a variety of architectures (with AVX2), and I would like at least to be able to provide a way to diagnose the problem if it happens.

Also, you are right, docker runs on a different computer:
```
$ docker run -it --entrypoint lscpu docker.io/regevsch/gamma_smc:v0.2-alpha
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               GenuineIntel
  Model name:            Intel Xeon Processor (Skylake, IBRS)
    CPU family:          6
    Model:               85
    Thread(s) per core:  1
    Core(s) per socket:  1
    Socket(s):           4
    Stepping:            4
    BogoMIPS:            5200.05
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_t
                         sc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer a
                         es xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriori
                         ty ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx51
                         2bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat umip pku ospke md_clear arch_capabilities
Virtualization features:
  Virtualization:        VT-x
  Hypervisor vendor:     KVM
  Virtualization type:   full
Caches (sum of all):
  L1d:                   128 KiB (4 instances)
  L1i:                   128 KiB (4 instances)
  L2:                    16 MiB (4 instances)
  L3:                    64 MiB (4 instances)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-3
Vulnerabilities:
  Itlb multihit:         Not affected
  L1tf:                  Mitigation; PTE Inversion; VMX flush not necessary, SMT disabled
  Mds:                   Mitigation; Clear CPU buffers; SMT Host state unknown
  Meltdown:              Mitigation; PTI
  Mmio stale data:       Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl and seccomp
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling
  Srbds:                 Not affected
  Tsx async abort:       Mitigation; Clear CPU buffers; SMT Host state unknown
```

This is also a virtual machine, but a different computer.

**Comment by dtrudg** [comment]
> I cannot compile without `-mavx2` (I use special AVX2 instructions). But indeed when I compile without `-march-native` it works well. I will explicitly use `-march=x86-64` for the docker image, which seems to work.
> 
> It would still be good to understand why this failed. Future users of my image should be able to run this image on a variety of architectures (with AVX2), and I would like at least to be able to provide a way to diagnose the problem if it happens.

Ultimately this isn't a Singularity issue - the same error would occur without containers at all, if the mix of machine / VM CPUs was the same. If Docker was running on the Broadwell machine, you'd also see the issue there.

The root cause is that the compiler, when run with `-march-native` is detecting that the CPU in the Docker build environment supports an instruction that the VM machine you run `singularity` on does not. The code is compiled and the executable uses this instruction.

The VM where the Docker container runs is providing Skylake level features, while the VM where Singularity runs is providing Broadwell level features. So, some CPU instruction added between Broadwell and Skylake is the culprit. You may be able to interrogate the binary, or run it with some tracing to see exactly what instruction it is that causes the failure.

If you know that you won't ever need to run on older than a Broadwell CPU, then you can probably use `-march=broadwell` to get code the will run across all of these machines, but is more optimised than with `march=x86-64`.

I'll close the issue now as it's not a Singularity problem, but please feel free to reopen (or open a new issue) if you come across anything definitely Singularity specific. Unfortunately instruction support is a generic issue in HPC enviroments where optimised code is important, but where it may be run across multiple machines. You may be able to compile for multiple architectures with differently optimized code paths in a single binary. This is sometimes the type of thing that a local HPC support group can advise on.
