### ISSUE TITLE
echo does not work in %startscript

### ISSUE THREAD

**Issue by Heng-Zhou** [sylabs/singularity#2501]
**Version of Singularity**
What version of Singularity are you using? 
`singularity-ce version 4.0.2-jammy`

**Describe the bug**
echo does not work in %startscript section.

**To Reproduce**
This is the def file:
```
BootStrap: library
From: ubuntu

%post
   apt-get -y update
   apt-get -y install cowsay lolcat less

%environment
   export LC_ALL=C
   export PATH=/usr/games:$PATH

%runscript
   date | cowsay | lolcat

%startscript
   echo "@@@@ $(pwd) @@@@"
```
`singularity build --force lolcow.sif lolcow.def` to build the container.
`singularity instance start lolcow.sif instance1` to run the container as an instance.

**Expected behavior**
According to [this document](https://docs.sylabs.io/guides/4.0/user-guide/running_services.html):
![image](https://github.com/sylabs/singularity/assets/111557423/f1ccda8f-bc3d-4c4e-a1b1-1415083bb3de)
echo command should've printed out something on the screen. But nothing was output except "INFO:    instance started successfully."

So, what's the matter?

**OS / Linux Distribution**
Which Linux distribution are you using?
```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Installation Method**
I went to https://github.com/sylabs/singularity/releases, downloaded `singularity-ce_4.0.2-jammy_amd64.deb` and installed using `sudo dpkg -i` command.

**Additional context**
N/A

**Comment by dtrudg** [comment]
This isn't a bug. Because they run in the background, the standard ouptut and standard input of instances are redirected to log files. You need to look in these files, the output will not be on the screen.

This is fully documented in the user guide, instance section: 

https://docs.sylabs.io/guides/4.0/user-guide/running_services.html#instance-logs

**Comment by Heng-Zhou** [comment]
> This isn't a bug. Because they run in the background, the standard output and standard error of instances are redirected to log files. You need to look in these files, the output will not be on the screen.
> 
> This is fully documented in the user guide, instance section:
> 
> https://docs.sylabs.io/guides/4.0/user-guide/running_services.html#instance-logs

Running in the background does not mean the command cannot output to terminal. An example is 
`echo "background can output" &`
Here, echo is running in background, but it can still output to terminal.

Of course, if it is redirected, then there is no output. But I think this designed behavior is counter-intuitive because most people expect to see the output in terminal.

**Comment by dtrudg** [comment]
I'm afraid that this is by design, and isn't a behaviour that will be changed.

The instance functionality is designed to run long-running services, where output is generally expected to be to log files. If you run e.g. a web server in an instance, it is unlikely that you would want all of the log output to appear on your terminal. It would clash with whatever you contined to do in that terminal.

When you run `echo "hello" &` in the background from a shell it is attached to a terminal. If the terminal is closed then the command would stop. We don't want a container to exit if you close the terminal where you started it - therefore the way it is run in the background is different to using `&` in a shell.

You can think of starting an instance to be more like running a command with `nohup`, which will also redirect the output to a file, and avoid the command being stopped if the terminal is closed.

**Comment by Heng-Zhou** [comment]
I don't know the details of the design of Singularity, but in my memory, if a process forks a new process, this sub-process does not have to exit together with the parent-process (more often it is re-parented by the system). Also, my memory is that sub-process can output to the parent-process's terminal because the file descriptor is inherited. So if the terminal is closed, the only consequence is that the user cannot see any output from the sub-process (the commands started in %startscript section). Anyway, I don't know the details of the design of Singularity, so there may be some complexity I didn't understand. I will take a look at overlay and other suggestions you gave. Thanks for your replies.

**Comment by dtrudg** [comment]
> I don't know the details of the design of Singularity, but in my memory, if a process forks a new process, this sub-process does not have to exit together with the parent-process (more often it is re-parented by the system). Also, my memory is that sub-process can output to the parent-process's terminal because the file descriptor is inherited. So if the terminal is closed, the only consequence is that the user cannot see any output from the sub-process (the commands started in %startscript section). Anyway, I don't know the details of the design of Singularity, so there may be some complexity I didn't understand. I will take a look at overlay and other suggestions you gave. Thanks for your replies.

Did you mean to post this reply on #2506?

FWIW - the issue isn't really handling the exit of a process writing to the terminal. The issue is wiring up the that process to the stdin / stdout of the container. This involves quite a lot of work, as with containers we cross Linux namespace boundaries, we don't just spawn subprocesses but sometimes execve replacing the parent, and consequently may need to do things like pass file descriptors through sockets. or write/read to sockets directly in order to obtain stdin / stderr where it might be needed outside of the container process for display to a terminal. Ultimately it's more complex, and there are rather more Linux specifics involved, than discussed in guides to programming single UNIX processes.

If you are ever interested in reading a bit more about how Singularity works, this audit has some diagrams / information that give an overview of how things flow: https://www.ideals.illinois.edu/items/111708 

E.g.

<img width="680" alt="image" src="https://github.com/sylabs/singularity/assets/4522799/b020b152-93c9-41fe-8bb2-8bb522070d91">

Cheers.
