### ISSUE TITLE
Merge contents in the container with those in bind mounted directories on host

### ISSUE THREAD

**Issue by Heng-Zhou** [sylabs/singularity#2502]
**Is your feature request related to a problem? Please describe.**
Ticket #2483

**Describe the solution you'd like**
First, thank dtrudg for replying my ticket and explaining to me why the file I added into container does not show in $HOME.

I understand in current Singularity, bind mounted directory on host will completely replace the one in container. But how about letting users have an option to be able to merge the contents in the container with those in bind mounted directory on host, because sometimes users really need this function (some software read settings from $HOME and users wish to create a container with some settings already saved in $HOME)?

**Describe alternatives you've considered**
N/A

**Additional context**
Some software read settings from $HOME (which is a convention) and users wish to create a container with some settings already saved in $HOME directory. Then, the user wishes to save the work to the host running the container, say, in $HOME/project. So, simply disabling bind mounting $HOME is not a good solution.

**Comment by dtrudg** [comment]
In order to merge external directories with the contents of a container, SingularityCE already supports overlays.

To get the behaviour you want, merging the host $HOME with the container $HOME, you could try to:

* Disable the default bind mount of $HOME into the container (`--no-mount home,cwd`)
* Instead, add an overlay of the host $HOME onto the container $HOME (see https://docs.sylabs.io/guides/4.0/user-guide/persistent_overlays.html#directory-overlay)

However...

> Some software read settings from $HOME (which is a convention) and users wish to create a container with some settings already saved in $HOME directory.

... this won't generally work well, even with the above, because with Singularity, your home directory path in the container is the same as on the host, by default. Your settings files in the container will only be at the right place when the $HOME directory on the host is the same as in the container. If another user uses the container, or you run it on a system with a different `$HOME` directory path, it will not work as expected.

It's important to note that Singularity was written specifically to support different workflows to Docker. It's expected with Singularity that license files etc. will be kept in the host `$HOME` and automatically bind mounted in, to avoid containers become specific to one user, or leaking license to the public etc.

As mentioned elsewhere, I strongly advise writing your Dockerfiles that will  be used with Singularity so that no software or settings in the container are installed in `$HOME` in the container.

This is documented as a best practice: https://docs.sylabs.io/guides/4.0/user-guide/persistent_overlays.html#directory-overlay

As an aside - rather than open multiple issues, it would be better to approach this in the Disccussions Q&A section, giving full details of what it is you are trying to accomplish. If any feature requests result from discussion there, then we can think about tracking them as issues.

**Comment by Heng-Zhou** [comment]
> In order to merge external directories with the contents of a container, SingularityCE already supports overlays.
> 
> To get the behaviour you want, merging the host $HOME with the container $HOME, you could try to:
> 
>     * Disable the default bind mount of $HOME into the container (`--no-mount home,cwd`)
> 
>     * Instead, add an overlay of the host $HOME onto the container $HOME (see https://docs.sylabs.io/guides/4.0/user-guide/persistent_overlays.html#directory-overlay)
> 
> 
> However...
> 
> > Some software read settings from $HOME (which is a convention) and users wish to create a container with some settings already saved in $HOME directory.
> 
> ... this won't generally work well, even with the above, because with Singularity, your home directory path in the container is the same as on the host, by default. Your settings files in the container will only be at the right place when the $HOME directory on the host is the same as in the container. If another user uses the container, or you run it on a system with a different `$HOME` directory path, it will not work as expected.
> 
> It's important to note that Singularity was written specifically to support different workflows to Docker. It's expected with Singularity that license files etc. will be kept in the host `$HOME` and automatically bind mounted in, to avoid containers become specific to one user, or leaking license to the public etc.
> 
> As mentioned elsewhere, I strongly advise writing your Dockerfiles that will be used with Singularity so that no software or settings in the container are installed in `$HOME` in the container.
> 
> This is documented as a best practice: https://docs.sylabs.io/guides/4.0/user-guide/persistent_overlays.html#directory-overlay
> 
> As an aside - rather than open multiple issues, it would be better to approach this in the Disccussions Q&A section, giving full details of what it is you are trying to accomplish. If any feature requests result from discussion there, then we can think about tracking them as issues.

I have no idea about Docker. I did not mean to ask Singularity to work the same way as Docker. I just want to ask Singularity to work the way a normal user would expect.

Why not let other people to listen to me, instead of closing my ticket in such a hurry? That you think unreasonable does not mean it is really unreasonable.

**Comment by dtrudg** [comment]
Sorry that you feel your thoughts have not been heard.


> I have no idea about Docker. I did not mean to ask Singularity to work the same way as Docker. I just want to ask Singularity to work the way a normal user would expect.

Apologies - most people who ask these questions are basing their understanding / expectations on how Docker works by default. I shouldn't have assumed this, and am sorry that I did.

> Why not let other people to listen to me, instead of closing my ticket in such a hurry? That you think unreasonable does not mean it is really unreasonable.

As I mentioned in the answer above, there is already a way to do this, using Singularity's support for overlays. Also, because of Singularity's long-term default behaviour, which we cannot change, putting files in `$HOME` while building a container will never work well unless a user runs with a large number of non-default flags. We don't want to encourage the creation of containers which require many runtime flags to work correctly, so it's unlikely we would add another option to merge $HOME when it's already possible using overlays.

Merging $HOME brings complexity. When files are written when the container is running, people may not understand they write out to the overlay (host $HOME), or the implications of an overlay being read-only etc.



> > As an aside - rather than open multiple issues, it would be better to approach this in the Disccussions Q&A section, giving full details of what it is you are trying to accomplish. If any feature requests result from discussion there, then we can think about tracking them as issues.

**Comment by Heng-Zhou** [comment]
Thank you for your reply. I don't mean to mess up the boundary between general discussion and bug report. When I wrote a issue ticket, I really thought it is a bug. Maybe my standard of bug is kind of too high -- basically anything in contradiction with a normal user's expectation is considered a bug in my side. But I will have your reply in mind, and try to conform to the regulation you defined. Thanks again for your replies and reference to overlay.
