### ISSUE TITLE
support passing multiple env files

### ISSUE THREAD

**Issue by cmatKhan** [sylabs/singularity#2744]
**Is your feature request related to a problem? Please describe.**

I would like to be able to pass environmental variables that are stored in separate files, eg:

```bash
            singularity exec --bind .:/app \
                             --env-file ./.envs/.local/.django \
                             --env-file ./.envs/.local/.postgres \
                             --env-file ./.envs/.local/.regulatory_data \
                             $django_sif bash -c 'cd /app && /start'
```

**Describe the solution you'd like**

The environmental variables from each file should be set in the container environment, with later files taking priority

**Describe alternatives you've considered**

Keeping the environmental variables in separate files can be useful, but of course this can be concatenated and provided to `--env-file` as it is currently implemented

**Comment by dtrudg** [comment]
Hi @cmatKhan - this seems like it'd be a useful feature. 

If you or anyone else would be interested in contributing a PR to implement it then I don't see any reason why it could not be merged.

Otherwise we'll keep it on the list of suggested features for future development, which we evaluate periodically.
