### ISSUE TITLE
singularityce is on conda-forge now

### ISSUE THREAD

**Issue by ngam** [sylabs/singularity#459]
*Note*: We encourage questions about usage of SingularityCE to be made via the Google Group or Slack channels. Other users frequent these communities, and may already have the answer to your question!

See: https://sylabs.io/resources/community for links.

**Type of issue**
E.g. test problem / technical debt / release tracking

**Description of issue**
Give a concise, but complete description of the issue here, with any information that might be needed to investigate, or act on it.

---

https://anaconda.org/conda-forge/singularityce
https://github.com/conda-forge/singularityce-feedstock

Given all the drama and confusion going on, I have decided to add singularityce to conda-forge. We've been maintaining singularity (proper?) for a while now and I thought we should have singularity, singularityce, and the newcomer apptainer available especially as things are developing. This is just fyi and you don't need to do anything. You're more than welcome to join me in maintaining --- just a pr away. And please feel free to let me know if you'd like me to address any issues, etc. or if you get complaints from users as they use singularityce from conda-forge.

(Unrelated: Will you ever support MacOS and Windows? I am only half-joking)

**Comment by dtrudg** [comment]
Thank you for doing this, and letting us know!

With regard to Windows - SingularityCE can be installed under WSL2 and is fully functional there. It's very straightforward now that we are shipping Ubuntu packages on the release page.

For Mac, the beta Singularity Desktop product was deprecated a while back, due to the complexities of shipping and maintaining a working Linux Virtual Machine configuration to run Singularity inside of. MacOS moves quickly, security changes often affect these types of environments, and the Intel / ARM split recently adds complexity. We (Sylabs) had an open email to the community about releasing the source for community led maintenance, but there was no interest at the time.

**Comment by ngam** [comment]
Thanks @dtrudg --- closing this for now.

And re win and osx, I think the current offering makes perfect sense for now (btw, Canonical has multipass.run which works super smoothy and super fast, and one can install Singularity inside a multipass instance as well). I think it may be a different conversation as the commercial aspects of this project (i.e. Sylabs) change, like wanting to capture more market from things like Docker, etc. but that will necessitate changing Singularity fundamentally, I reckon, to be able to run natively on a wide swath of OSs and filesystems and so on. 

Anyway, thanks for your commitment to this project --- and looking forward to more of Sylabs features as they become available :) I also hope this is the beginning of the end of the distracting drama 👍
