### ISSUE TITLE
singularity `--without-suid` build

### ISSUE THREAD

**Issue by ngam** [sylabs/singularity#475]
Hi again, @dtrudg,

I reached out about singularityce through conda-forge (https://github.com/sylabs/singularity/issues/459). I have been doing some testing to improve our build and I would like to discuss that with you. 

1. Can you clarify to me the exact need for `cgroup` namespace? I gather that without `cgroup` namespace enabled, singularity simply cannot work --- is that an accurate statement? Are there any alternatives?
2. Over at conda-forge, we build with the `--without-suid` flag. Thus, conda's singularity suffers from all the disadvantages documented [here](https://sylabs.io/guides/latest/user-guide/security.html). But does it have to? Is there any way to avoid converting SIF files to temporary sandboxes with a `--without-suid` installation? 

An as example, I get the following warning I `pull`,

```
$ singularity pull docker://ubuntu
INFO:    Converting OCI blobs to SIF format
WARNING: 'nodev' mount option set on SYSTEM_SCRATCH, it could be a source of failure during build process
INFO:    Starting build...
Getting image source signatures
Copying blob 7b1a6ab2e44d skipped: already exists  
Copying config e7132beceb done  
Writing manifest to image destination
Storing signatures
2021/12/10 17:16:18  info unpack layer: sha256:7b1a6ab2e44dbac178598dabe7cff59bd67233dba0b27e4fbd1f9d4b3c877a54
INFO:    Creating SIF file...
```

and the following warning as well when I `shell`,

```
$ singularity shell ubuntu_latest.sif 
INFO:    Converting SIF file to temporary sandbox...
WARNING: underlay of /etc/localtime required more than 50 (66) bind mounts

```

where `SYSTEM_SCRATCH` is the filesystem it is using. This takes a lot of time and sometimes renders singularity useless, especially compared with a system-wide installation, where these warnings wouldn't be produced. Can these issues be addressed at all, either by the user or by us during the build? I totally understand the issue with privilege vis-a-vis building, but this limitation here seems like easy to avoid, unless I am misunderstanding something fundamentally. 

Any help will be appreciated. And you and your team are again more than welcome to be part of the maintainers on the conda-forge side. Thanks!

---

*Note*: We encourage questions about usage of SingularityCE to be made via the Google Group or Slack channels. Other users frequent these communities, and may already have the answer to your question!

See: https://sylabs.io/resources/community for links.

**Type of issue**
E.g. test problem / technical debt / release tracking

**Description of issue**
Give a concise, but complete description of the issue here, with any information that might be needed to investigate, or act on it.

**Comment by dtrudg** [comment]
> 1. Can you clarify to me the exact need for `cgroup` namespace? I gather that without `cgroup` namespace enabled, singularity simply cannot work --- is that an accurate statement? Are there any alternatives?

The `cgroup` namespace is not required, nor is it actively used in SingularityCE at this time. What is *absolutely* required is the `mount` namespace... for set-uid and non-set-uid flows. This is a minimal requirement to implement any type of container.

Support for unprivileged user namespaces is required for an install without set-uid. This is because an unprivileged user must be inside a user namespace in order to create a new mount namespace, and establish the container filesystem mounts. You cannot create a container unprivileged without a user namespace. The mount namespace is to isolate the container filesystem from the host filesystem.

> 2. Over at conda-forge, we build with the `--without-suid` flag. Thus, conda's singularity suffers from all the disadvantages documented [here](https://sylabs.io/guides/latest/user-guide/security.html). But does it have to? Is there any way to avoid converting SIF files to temporary sandboxes with a `--without-suid` installation?

The filesystem inside a SIF is a SquashFS, which is mounted via the SquashFS driver in the kernel, and through a loop device. Neither of these is possible without root privileges. There is no way around this with SingularityCE at present. Without suid we can't perform the mount straight out of a SIF, so we have to extract the SIF to a directory, where we can then perform mounts inside the unprivileged user namespace.

In order to allow direct use of a SIF image unprivileged (and inside a user namespace) we would need to implement a FUSE (filesystem in user space) approach for SIF, which could probably be done mostly be integrating https://github.com/vasi/squashfuse

FUSE isn't without drawbacks, though. The code for projects like squashfuse is often less maintained than the kernel filesystem code. There is also a performance penalty from using FUSE vs a kernel mount. squashfuse also currently lacks support for multi-core decompression. A FUSE approach is definitely something we are looking into, though, for where it is beneficial.

**Comment by ngam** [comment]
Thanks for explaining, really appreciate it!!!

Does SingularityCE have any test to indicate the availability of user + mount namespaces availability before installing/building? So this may be potentially part of the problem for us: We build SingularityCe on systems (inside docker images) WITHOUT user+mnt namespaces enabled, and then we rely on relocation to make it work. Recently, I was building another package and I learned all of this --- I previously thought `lsns` lists the _enabled_ namespaces, but it apparently does NOT. What would be a user-end test to perform to check if user+mnt namespaces are enabled?

Okay, the extracting into a directory makes sense (similar to the explicit charliecloud strategy). Btw, I am not advocating for a specific solution, I am trying to understand where our bottleneck is. Do you think the slowdown due to extracting into a directory should be that significant? We are talking ~15 mins (sometimes significantly more) or more for a beefy image. Does the underlying filesystem matter significantly? Obviously Singularity will be used on HPCs where there are two filesystems usually: Lustre with vast storage and a "home" filesystem with only like 5-10 GB per user. So I would assume a user would eventually add Singularity in the lustre system (or equivalent, e.g. gpfs). What's your assessment? Could this be the underlying bottleneck then? 

I will soon do more personal testing on several personal machines to see if I could see any differences.

**Comment by dtrudg** [comment]
In the `mconfig` output you should see the checks....

```
=> running post-basechecks project specific checks ...
 checking: namespace: CLONE_NEWPID... yes
 checking: namespace: CLONE_FS... yes
 checking: namespace: CLONE_NEWNS... yes
 checking: namespace: CLONE_NEWUSER... yes
 checking: namespace: CLONE_NEWIPC... yes
 checking: namespace: CLONE_NEWNET... yes
 checking: namespace: CLONE_NEWUTS... yes
 checking: namespace: CLONE_NEWCGROUP... yes
```

> Okay, the extracting into a directory makes sense (similar to the explicit charliecloud strategy). Btw, I am not advocating for a specific solution, I am trying to understand where our bottleneck is. Do you think the slowdown due to extracting into a directory should be that significant? We are talking ~15 mins (sometimes significantly more) or more for a beefy image. Does the underlying filesystem matter significantly? Obviously Singularity will be used on HPCs where there are two filesystems usually: Lustre with vast storage and a "home" filesystem with only like 5-10 GB per user. So I would assume a user would eventually add Singularity in the lustre system (or equivalent, e.g. gpfs). What's your assessment? Could this be the underlying bottleneck then?

Very large images are often ones that also contain many thousands of small files. It takes a long time to extract these onto a parallel filesystem, like Lustre, as those filesystems are very inefficient for small files due to the massive metadata overhead, which requires round trips across the network for every small file etc. Straight NFS (which is quite common for $HOME) is also affected, but generally a bit less than Lustre, GPFS etc.

This metadata issue is actually one of the big benefits of SIF... running out of a SIF makes the metadata traffic local, and can speed up launch of e.g. python ML apps with loads of files versus a native install on the host.

This isn't something that can be easily worked around other than a) extracting to fast local disk (e.g. TMPDIR on SSD/NVMe), or b) implementation of FUSE SIF mounting.

**Comment by ngam** [comment]
> This metadata issue is actually one of the big benefits of SIF... running out of a SIF makes the metadata traffic local, and can speed up launch of e.g. python ML apps with loads of files versus a native install on the host.

I can confirm this. 

Okay, let me test this and get back to you. I will try the remote builder to assemble an image and see how that process goes. If this reduces the bottleneck, this is pretty significant and I think that'll be great.

**Comment by ngam** [comment]
Just a quick update: `mconfig` output says yes but when I try to run `singularity shell ubuntu_latest.sif` it doesn't go through.

```
=> running post-basechecks project specific checks ...
 checking: namespace: CLONE_NEWPID... yes
 checking: namespace: CLONE_FS... yes
 checking: namespace: CLONE_NEWNS... yes
 checking: namespace: CLONE_NEWUSER... yes
 checking: namespace: CLONE_NEWIPC... yes
 checking: namespace: CLONE_NEWNET... yes
 checking: namespace: CLONE_NEWUTS... yes
 checking: namespace: CLONE_NEWCGROUP... no
```

**Comment by dtrudg** [comment]
Well, the user namespace support can exist (the `CLONE_NEWUSER` flag exists)... but be disabled by a sysctl `user.max_user_namespaces` set to 0.... or because the call to create a user namespace is blocked somehow.

If you are running inside of Docker, you have to be using `--privileged` or it is blocked by the default syscall filtering etc.

On some distributions it's likely present but not enabled. See e.g. 

https://sylabs.io/guides/3.9/admin-guide/user_namespace.html#user-namespace-requirements

**Comment by ngam** [comment]
> the call to create a user namespace is blocked somehow

Yes, this is the only thing. I am not running in Docker (we do use --privileged flags when we build singularity for conda). I was testing in a RHEL controlled by admins (I don't have sudo rights). 

Okay, I think you answered all my questions for now. I will come back with more if I have more issues (closing this for now; will reopen here if something else comes up). As always, thanks very much!
