### ISSUE TITLE
kernel dmesg log overflow with new version

### ISSUE THREAD

**Issue by idesk2596** [sylabs/singularity#488]
### Version of Singularity:

What version of Singularity are you using? Run:

```
singularity-ce 3.9.1
```

Hi,

I have upgrade the kernel to 5.15.5 (Ubuntu 18.04) and starting to see below
prints in kernel log in each execution flooding the log..

```
...
loop1: detected capacity change from 0 to 1153056
loop1: detected capacity change from 1153056 to 1152984
overlayfs: "xino" feature enabled using 3 upper inode bits.
loop1: detected capacity change from 0 to 1153056
loop1: detected capacity change from 1153056 to 1152984
overlayfs: "xino" feature enabled using 3 upper inode bits.
loop1: detected capacity change from 0 to 1059808
loop1: detected capacity change from 1059808 to 1059736
overlayfs: "xino" feature enabled using 3 upper inode bits.
loop1: detected capacity change from 0 to 1059808
loop1: detected capacity change from 1059808 to 1059736
overlayfs: "xino" feature enabled using 3 upper inode bits.
..
```

The ```loop1: detected capacity change from``` prints when running SIF images only, nothing printed if sandbox. (squashfs?)
and ```overlayfs: "xino" feature enabled using 3 upper inode bits``` stops if ```enable overlay = no```
or if it is enabled and the overlay module option disabled:
 ```echo 'options overlay xino_auto=off' > /etc/modprobe.d/overlay.conf``` but not sure if this is desirable..

**Comment by dtrudg** [comment]
Hi @idesk2596 - these messages are normal informational messages in newer kernels. They show normal behavior - the squashfs and overlay modules just have more logging in new versions.

If you manually mount an image to a loop device you'll get the same capacity change message:

```
$ sudo mount -o loop test.ext3 testmount/

[ 3613.035303] loop0: detected capacity change from 0 to 200
```

The `xino` feature is related to tracking inode numbers across different devices, and it is an advantage that it works on overlayfs in newer kernels. The message is for information only, and you should not disable the xino support.

Nothing can be done in SingularityCE to hide these messages because they are a consequence of normal operation.
