### ISSUE TITLE
pythonpath in container broke

### ISSUE THREAD

**Issue by Yoark** [sylabs/singularity#491]
using version 3.8.5-1.el7

I was building docker image locally then upload to docker hub, and using singularity to pull it and use the image on my school cluster.

had a `ENV PYTHONPATH=/usr/src/env_drop/build:/usr/src/Recurrent-VLN-BERT:/usr/src/env_drop/Oscar`
in my dockerfile, which helps python find a library.
It works perfectly, meaning, I could go into the image and do
```
>>> python3
>>> import xxx
>>> (success)
```

But it seems after the November 29th update on my cluster. This is broken, and python could not find 'xxx' anymore.

**Comment by dtrudg** [comment]
Hi @Yoark  - version 3.8.5 was only released from the https://github.com/apptainer/singularity/ repository. This sylabs/singularity repository, where we release as SingularityCE, is the other side of a fork.

SingularityCE's last 3.8 version was 3.8.4, and we've since moved on to 3.9.2 as the latest version.

If your issue is specific to `3.8.5-1.el7` then you will need to raise it with the other repository linked above. If the issue occurs with SingularityCE 3.9 also, we can certainly help you here.
