### ISSUE TITLE
Adding pip package to an existing singularity image with sandbox

### ISSUE THREAD

**Issue by blazejdolicki** [sylabs/singularity#506]
**Type of issue**
question

**Description of issue**
I'm currently using a singularity image that i received from my colleague and I need to use a pip package that is not installed there. As far as I understand, I could easily add the required package to the image using sandbox, but it doesn't seem to work properly.
Here are the detailed steps I took:
make the sandbox folder
```
$ singularity build --sandbox <sandbox-folder> <current-image>.sif
```
access the folder through shell
```
$ singularity shell --writable <sandbox-folder>
```
inside the shell: install the package
```
Singularity> python -m pip install seaborn
```
The installation looks succesful and when I run 
```
Singularity> python -c "import seaborn; print(seaborn.__version__)"
``` 
the output is
```
0.11.2
```
Then I build a new image from sandbox that should contain the required package
```
singularity build <new-image>.sif <sandbox-folder>/
```
And open the shell of the image and run the same command
```
$ singularity shell <new-image>.sif
Singularity> python -c "import seaborn; print(seaborn.__version__)"
```
I get an error
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'seaborn' has no attribute '__version__'
```
The error is the same when using any seaborn function instead `seaborn.__version__` such as `seaborn.load_dataset()`. After some digging it appears that the problem is caused by the permissions to the seaborn folder. 
 
When I check the permissions of packages of conda with
```
ls -la /users/hissl/miniconda3/lib/python3.8/site-packages/
```
all the package folder seem to have permissions `drwxr-xr-x` while seaborn folder has permissions `drwx------`. So for some reason the newly installed package does not have read permissions. Do you know any reason why that could be the case and how i could solve this problem?

**Comment by dtrudg** [comment]
This path `/users/hissl/miniconda3/lib/python3.8/site-packages/` is inside the container?

Before you do the `pip install` check the output of `umask` on your host, and in the container. What is it? The umask sets the default permissions for new files. If the umask on your host is restrictive then the new files in the container may be created so they can't be read once they are owned by root in the SIF.

You can try specifying the `--no-umask` flag when you `singularity shell` in to the container so that the umask applied in the container is a default permissive one.

**Comment by blazejdolicki** [comment]
Thank you for a quick reply. Indeed `umask`s of my host and container were 0077. When I changed umask to 0022 in the sandbox shell, uninstalled and reinstalled seaborn and built the container, the problem was fixed. As far as I know for singularity 3.6 the default umask was 0022 but for later versions singularity uses the umask of the host and that caused the problem.

**Comment by dtrudg** [comment]
Yes, the behavior has been to pass the umask in by default since 3.7.0. The change was made to fix issues caused by unexpected permissions when creating files inside bind mounts from hosts with umasks set for a purpose. It was requested by many, and generally agreed the default should be to follow the host's umask by default

https://github.com/sylabs/singularity/blob/master/CHANGELOG.md#v370---2020-11-24

> When actions (run/shell/exec...) are used without --fakeroot the umask from the calling environment will be propagated into the container, so that files are created with expected permissions. Use the new --no-umask flag to return to the previous behaviour of setting a default 0022 umask.
