### ISSUE TITLE
CDASH CTest inside singularity container

### ISSUE THREAD

**Issue by denisbertini** [sylabs/singularity#522]
I would like to use the suite *CTEST/CDASH* with *CMAKE* inside a singularity container 
 and submit the tests results to a *dashboard*.
Is it possible to do that inside a singularity container or is there some limitations one should be 
aware of?
Has anyone some experience of using CTEST/CDASH together with singularity?

**Comment by dtrudg** [comment]
Hi @denisbertini - as this is a question regarding the usage of SingularityCE, rather than an issue with the software, or a feature request, it would be better to ask in the community channels:

- Our Slack workspace https://singularityce.slack.com
- Our Google Group https://groups.google.com/g/singularity-ce

These are the best locations to ask about how to use Singularity, or for help with application specific issues. Questions will be seen by a range of users who may have input. GitHub issues are only seen by those who open them, and are best for bug reports, and feature requests.
