### ISSUE TITLE
Build for different hardware

### ISSUE THREAD

**Issue by vakker** [sylabs/singularity#585]
Hi,

Sorry if this is a silly question, but how does Singularity handle builds for different hardware? E.g. if I build the container on my laptop (that requires compilation of some libraries) and run the container on a cluster that has different hardware (CPU, GPU), then how can I take advantage of hardware-optimised compilation? 

Thanks!

**Comment by dtrudg** [comment]
Hello. Usage questions that are not bug reports or feature requests are best directed to the Slack workspace or mailing list, where a community of users will see them and may be able to give you some guidance from their experience.

https://sylabs.io/singularity#community

With regard to the question, Singularity does not influence the build at all with regard to hardware detection etc. If you need to build a container for a different micro-architecture, or different GPU etc. then the definition file you use to build will need to set compiler flags etc. that are appropriate for the target system.

Some compilers may allow you to compile so that binaries contain optimizations for different CPUs in different code paths (a fat binary). 

I would suggest getting involved in one of the community spaces linked above, and giving some detail of the type of software you are trying to work with, the environments you need to run it in, and engage in discussion with other users about how they approach this.
