### ISSUE TITLE
Docker image with Julia to Singularity binaries missing

### ISSUE THREAD

**Issue by nevesLiliane** [sylabs/singularity#590]
Hi, I'm trying to use the a Docker image with adcme [kailaix/adcme](https://hub.docker.com/r/kailaix/adcme), and with docker using the command `docker run -ti kailaix/adcme` it runs fine, opening a Julia prompt

but when I try with Singularity(`singularity run docker://kailaix/adcme`), after creating the SIF file, SIngularity does not find the julia installation inside the container. I think  it has to do with $HOME, since the docker container seems to be pointing to a different $HOME when compared to singularity. I tried setting it from the outside with no results. The container only prints `exec '@'`
Also, I did an `inspect --list-apps` on the created SIF and it seems to have nothing inside it.

If I'm doing anything wrong, please help and thanks in advance.
I'm not sure it this is the right place to send this problem, if not, I'm sorry, I wasn't able to send it in the google group

**Comment by dtrudg** [comment]
This container is expecting to be run as `root` and is installing things into `/root`. Because singularity runs containers under your own user account, and the user inside matches the user outside, the files under `/root` aren't being found on PATH etc.

I can't really offer much advice on adapting it, as the Dockerfile for that container begins with an `ADD` line, copying files directly in from the host. You cannot adapt it and build it again without having access to those files.

You can try to build a SIF from the docker image, and open up permissions on the `/root` directory by using `chmod` in the `%post` block. But the software may still expect to be run as the `root` user, so more work may be required.

See https://sylabs.io/guides/latest/user-guide/singularity_and_docker.html#best-practices-for-docker-singularityce-compatibility for some information around limits of Docker container compatibility with Singularity.

Note also that our Slack channel and mailing list are generally a better place to ask questions about usage, or specific applications. GitHub is primarily for bug reports and feature requests.

https://sylabs.io/singularity#community

**Comment by nevesLiliane** [comment]
Thank you so much, you really helped
Another question: Is there any way I can find the Dockerfile of an image from the docker image?
My question is because you cited that the image starts with `ADD` but the [Dockerfile](https://github.com/kailaix/ADCME.jl/blob/master/Dockerfile) I found does not use this specific command

And thank you so much again

**Comment by dtrudg** [comment]
> Thank you so much, you really helped Another question: Is there any way I can find the Dockerfile of an image from the docker image? My question is because you cited that the image starts with `ADD` but the [Dockerfile](https://github.com/kailaix/ADCME.jl/blob/master/Dockerfile) I found does not use this specific command

The easiest thing is to look on Docker Hub. From the 'tags' tab if you click the link for a specific tagged container you'll see how it was built. E.g.:

https://hub.docker.com/layers/kailaix/adcme/latest/images/sha256-94258c1f9a0012e4a872906216f410525f44e36832533ed630da854cf4939c01?context=explore

**Comment by nevesLiliane** [comment]
Thanks!
