### ISSUE TITLE
Failed to execute source /etc/profile

### ISSUE THREAD

**Issue by Qiyu8** [sylabs/singularity#666]
**Version of Singularity**
3.9.6

**Describe the bug**
When the @post section contains source /etc/profile, A fatal error occurred
+ source /etc/profile
++ '[' -x /usr/bin/id ']'
++ '[' -z 0 ']'
+++ /usr/bin/id -un
++ USER=root
++ LOGNAME=root
++ MAIL=/var/spool/mail/root
++ '[' 0 = 0 ']'
++ pathmunge /usr/sbin
++ case ":${PATH}:" in
++ pathmunge /usr/local/sbin
++ case ":${PATH}:" in
+++ /usr/bin/hostnamectl --transient
++ HOSTNAME=
**FATAL:   While performing build: while running engine: exit status 1**

**To Reproduce**
This is my recipe:
BootStrap: docker
From: openeuler/openeuler

%post
yum install -y environment-modules git
source /etc/profile

This is my command:
singularity build hello.sif hello.def

**Expected behavior**
A sif file should generated

**OS / Linux Distribution**
NAME="openEuler"
VERSION="20.03 (LTS-SP2)"

**Installation Method**
source
**Additional context**
Anything else which might be relevant. E.g. if the bug only occurs on a specific filesystem, or kernel version etc.

**Comment by dtrudg** [comment]
This isn't really a bug in SingularityCE..

In the `/etc/profile` of this container there is the following line:

```
HOSTNAME=`/usr/bin/hostnamectl --transient  2>/dev/null`
```

If you try and run the command in the container, it's apparent that the `/usr/bin/hostnamectl` binary is not present...

```
Singularity> HOSTNAME=`/usr/bin/hostnamectl --transient`
bash: /usr/bin/hostnamectl: No such file or directory
```

Our `%post` scripts run so that they fail on the first error. To ignore the error use `|| true`.

E.g. use `source /etc/profile || true`

Ideally the `/etc/profile` should be fixed to test for the binary's presence before attempting to call it, if it may not be present.

**Comment by Qiyu8** [comment]
Thanks for your answer, `source /etc/profile || true` works! please feel free to close.
