### ISSUE TITLE
Archives removed from older releases

### ISSUE THREAD

**Issue by rcannood** [sylabs/singularity#68]
**Version of Singularity**
3.2.1

**Describe the bug**
singularity-3.2.1.tar.gz file has been removed from sylabs/singularity repository.

**To Reproduce**
```
SINGULARITY_VERSION=3.2.1
wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz
```

**Expected behavior**
I expect the tar.gz file to be downloaded.

**OS / Linux Distribution**
Ubuntu 20.04

**Installation Method**
Irrelevant

**Additional context**
I've been downloading this archive as part of a CI script, but it seems the archives were removed from older releases.

**Comment by dtrudg** [comment]
Hi @rcannood - sylabs/singularity is now a fork of hpcng/singularity. 

Nothing has been deleted. Previously sylabs/singularity was a redirect to hpcng/singularity as the code was contributed to the hpcng organization around 1 year ago. Due to the recent fork that redirect is no longer in place.

All the older releases are still present on the other side of the fork. They are found at https://github.com/hpcng/singularity/releases

**Comment by rcannood** [comment]
Aha, thanks!
