### ISSUE TITLE
No nvidia libraries found inside the container

### ISSUE THREAD

**Issue by Qiyu8** [sylabs/singularity#685]
**Version of Singularity**
3.9.6

**Describe the bug**
The GPU version of lolcow.sif file is successfully generated, But I didn't find any cuda libraries inside the container's /usr/local directory, only nvidia-* is copied into /usr/bin:

**To Reproduce**
1. generate sif file using the following recipe:
```
Bootstrap: docker
From: ubuntu:16.04
%post
apt-get -y update
apt-get -y install cowsay lolcat
%environment
export LC_ALL=C
export PATH=/usr/games:$PATH
%runscript
date | cowsay | lolcat
```

2.build the container:
singularity build --nv --nvccli lolcow.sif lolcow.def

**Expected behavior**
cuda libraries should copied from host to container.

**OS / Linux Distribution**
Centos 8

**Installation Method**
source.

**Additional context**
I have successfully installed nvidia-container-cli.

**Comment by dtrudg** [comment]
Building with `--nv` only binds the libraries into the container at build time, so they are available to any steps in the build.. It does not copy the libraries into the container. You need to `run/shell/exec` to bring the libraries into the container at runtime. This is the expected behaviour.

If you want to build a container that includes the CUDA runtime, look into starting from the NVIDIA CUDA docker hub images: https://hub.docker.com/r/nvidia/cuda

**Comment by Qiyu8** [comment]
@dtrudg Thanks, found nvidia hpc containers from [here](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/nvhpc).
