### ISSUE TITLE
Cannot use Singularity within a `docker build`

### ISSUE THREAD

**Issue by stevekm** [sylabs/singularity#694]
copying this Issue here since it got auto-closed at https://github.com/apptainer/singularity/issues/6427

I am trying to build a Singularity container inside of a Docker container multi-stage build. I am using `docker build` to compile a simple Go (Golang) program, which I then want to package into a `.sif` Singularity container file. Somehow, I also want to save the `.sif` file to the host system, though I have not gotten that far. Right now, it breaks before it finishes making the `.sif` file.

my source files look like this;

- `hello.def`

```
Bootstrap: docker
From: alpine:3.15

%files
    /hello /hello

%post
    apk add bash
```

- `Dockerfile`

```
## Build Golang app
##
FROM golang:1.16-alpine AS build

WORKDIR /app

RUN echo 'module hello' > go.mod && echo "go 1.16" >> go.mod

RUN echo 'package main' > hello.go && \
echo 'import "fmt"' >> hello.go && \
echo 'func main() {' >> hello.go && \
echo 'fmt.Printf("hello, world\n")' >> hello.go && \
echo '}' >> hello.go

RUN go build -o /hello

COPY hello.def /hello.def

##
## Build Singularity container
##
# need alpine for using bash, otherwise use scratch
FROM singularityware/singularity:v3.3.0
COPY --from=build /hello /hello
COPY --from=build /hello.def /hello.def
RUN singularity build /hello.sif /hello.def

Build command & error messages:

$ docker build -t hello --file Dockerfile .
...
Step 10/10 : RUN singularity build /hello.sif /hello.def
 ---> Running in 85c920607ead
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:df9b9388f04ad6279a7410b85cedfdcb2208c0a003da7ab5613af71079148139
 2.68 MiB / 2.68 MiB  0s
Copying config sha256:13278536a0c1e9ace25e40a736808e9fb711b9521757eb57769dc30fd2cb1b15
 585 B / 585 B  0s
Writing manifest to image destination
Storing signatures
ERROR  : Failed to unshare root file system: Operation not permitted
FATAL:   While performing build: while running engine: exit status 1
The command '/bin/sh -c singularity build /hello.sif /hello.def' returned a non-zero code: 255
```

It looks like I hit this same error previously here https://github.com/apptainer/singularity/issues/632#issuecomment-350338195 but it was never resolved and the Issue was Closed. 

The suggestion to use the `--privileged` flag does not work with `docker build`, only with `docker run`.

Any idea on how to resolve this?

**Comment by dtrudg** [comment]
I'm afraid that there isn't anything we can do on the Singularity side of things here, since we must have the ability to create a mount namespace, which is what Docker build is blocking giving rise to that error message. However, it appears that privileged builds are possible with Docker using buildx: https://github.com/moby/moby/issues/1916#issuecomment-530278444

You might also be interested in the new `scs-build` tool, which can be used to perform a remote build of a def file to a sif, using the Sylabs Cloud remote build service without needing to install Singularity itself. See https://sylabs.io/2022/03/introducing-scs-build However you cannot copy in from a Docker build into the Singularity container like that. You would instead perform the build of your app inside the Singularity def file entirely, retrieving source code from a public repo (Singularity also support multi stage builds). I appreciate this may not be appropriate for your needs, though.

**Comment by stevekm** [comment]
@dtrudg thanks for the reply, looks like this was the solution for me; 

> You would instead perform the build of your app inside the Singularity def file entirely

I did not realize that [multi-stage builds](https://sylabs.io/guides/3.9/user-guide/definition_files.html#multi-stage-builds) were also a thing in Singularity. I changed it to this;

- `hello.def`

```
Bootstrap: docker
From: golang:1.16
Stage: builder

# using docker run --rm -ti -v $PWD:/host 
%files
    /host/hello.go /hello.go
    /host/go.mod /go.mod

%post
    go build -o /hello /hello.go


# Install binary into the final image
Bootstrap: docker
From: alpine:3.15
Stage: final

# install binary from stage one
%files from builder
  /hello /bin/hello

%post
    apk add bash

```

build command: 

```
$ docker run --privileged --rm -ti -v $PWD:/host \
	quay.io/singularity/singularity:v3.7.1 \
	build \
	/host/hello.sif /host/hello.def
```

Looks like it works now. Feel free to close this Issue. Thanks.
