### ISSUE TITLE
Remove Darwin Support

### ISSUE THREAD

**Issue by tri-adam** [sylabs/singularity#90]
The SingularityCE code base currently has partial support on Darwin (macOS), aimed at supporting Singularity Desktop (Singularity on macOS via virtualization.) Although Singularity Desktop is no longer maintained, we continue to build, test and maintain Darwin code in the SingularityCE code base.

It is of course possible to run Singularity on Darwin via Vagrant, as documented in the [SingularityCE Admin Guide](https://sylabs.io/guides/3.8/admin-guide/installation.html#installation-on-windows-or-mac). A notable exception is Macs built on Apple Silicon (#66), but since Singularity Desktop has never been supported on this platform either, this is not a loss of support, rather a continued absence.

Given the above, I believe we should consider removing Darwin support from the code base.

**Comment by dtrudg** [comment]
I would agree that removing Darwin support at this time is probably the way to go. We announced the end of Singularity Desktop nearly one year ago now - https://groups.google.com/a/lbl.gov/g/singularity/c/MSsOy6TkkQY/m/vrJWcbkFBQAJ

To date there hasn't been an indication that it'll be possible to support via community contribution, and the landscape becomes trickier with each new macOS release (tightened security, notarization stuff etc.) as well as the arrival of Apple Silicon.

Most clusters are still AMD64, rather than ARM64. I'd guess this will be true for some time, meaning that a native macOS version of Singularity has less utility over time as people upgrade their machines.

Running Singularity on an M1 mac would be an interesting way to build form ARM clusters in future, but this can be accommodated via a Vagrant based approach once that is supported on these machines somehow.
