### ISSUE TITLE
Password to run "shell" command

### ISSUE THREAD

**Issue by wynstep** [sylabs/singularity#92]
Hi there,
I was wondering if anyone can help. I have created a singularity image with custom scripts inside that I would like to be protected from reading.

Is there a way I can exec the singularity image without any password BUT requires a decryption password just for accessing to the images source through the "shell" command?

Many thanks!

**Comment by dtrudg** [comment]
Hi @wynstep - I'm afraid there is no way to effectively do this. In order to run a container it must be decrypted, and the user can then access/extract the content even if the `shell` command only is locked down. 

Encryption of the container is useful to ensure that only the intended user of a container can access what's inside it.

If you need to restrict access by the intended user to the custom scripts you would probably need to implement some kind of application-level encryption to protect those scripts.

**Comment by wynstep** [comment]
> Hi @wynstep - I'm afraid there is no way to effectively do this. In order to run a container it must be decrypted, and the user can then access/extract the content even if the `shell` command only is locked down. E.g. they could `mount` the container image directly and copy the files out.
> 
> Encryption of the container is useful to ensure that only the intended user of a container can access what's inside it.
> 
> If you need to restrict access by the intended user to the custom scripts you would probably need to implement some kind of application-level encryption to protect those scripts.

Alright, thank you! I'll try to think to another solution.
