### ISSUE TITLE
how to execute a for loop in singularity exec or?

### ISSUE THREAD

**Issue by bioinformzhang** [sylabs/singularity#991]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity --version
singularity version 3.8.3-1.el7
```

### Expected behavior
```
$ singularity pull docker://centos:centos7

$ singularity  shell centos7_latest.sif 
Singularity> for i in 1 2 3; do echo $i; done
1
2
3
```

### Actual behavior
```
$ singularity  exec centos7_latest.sif  for i in 1 2 3; do echo $i; done
-bash: syntax error near unexpected token `do'
```

the for loop works in singularity shell, but don't do that in singularity exec.
Is there any way to execute the loop in singularity exec

Thank you for giving your soul!

**Comment by dtrudg** [comment]
Hello, as this is a question about usage of Singularity, rather than a bug report or feature request, it is best asked on the mailing list or in the Slack Channel. For links see:

https://sylabs.io/singularity/

Regarding your question, `exec` directly runs an executable. It does not run commands through a shell, so shell constructs like a for loop will not work. To use exec and execute shell constructs, you would have to `exec` a shell, and then pass it the shell code:

```
01:48 pm $ singularity exec centos_7.sif sh -c 'for i in 1 2 3; do echo $i; done'
1
2
3
```
